### ISSUE TITLE
弱弱地问一下，这个主题怎么使用？

### ISSUE THREAD

**Issue by midiao** [newraina/typecho-theme-NexTPisces#1]
下面使用说明中的"解压上传"是什么意思？

**Comment by newraina** [comment]
@midiao 你的博客程序得是Typecho才行，在Typecho主目录下有一个usr文件夹，打开它里面有一个themes文件夹，把这个主题解压后的文件夹丢进themes文件夹里，上传文件，然后进你的博客后台启用主题，就OK了。
