### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by feedeve** [newraina/typecho-theme-NexTPisces#11]
第一个问题是 我在后台无法使用头像？
第二个问题是点击左侧栏的文章  分类  标签 都报404 忘有空解决一下 。 谢谢！

http://www.xufat.com/

**Comment by newraina** [comment]
谢谢指出！有空我看一下

**Comment by feedeve** [comment]
谢谢楼主，解决了。我看了其他人的评论后 下午自己倒腾了会没问题了。 至于头像我直接在PHP 改了URl了。  
 PS 建议楼主简介写明白一点，是在独立页面里面添加 ：
新建一个名叫“分类”的页面 ，缩略名（标题下方URL空白处）为categories，自定义模板选择categories
新建一个名叫“归档”的页面 ，缩略名（标题下方URL空白处）为archive，自定义模板选择archives
新建一个名叫“标签“的页面 ，缩略名（标题下方URL空白处）为tags，自定义模板选择tags

因为在管理里面也有类似的选项。

因为是第一次玩Typecho，走了不少弯路。
不过还是非常感谢你提供这么好的主题。
