### ISSUE TITLE
搜索功能的问题

### ISSUE THREAD

**Issue by zhyt0520** [newraina/typecho-theme-NexTPisces#12]
输入内容回车后，右侧只显示标题“包含关键字 ** 的文章”，下面出不来具体的内容，请问我该如何查找问题所在？

**Comment by newraina** [comment]
这个应该是确实没有符合条件的文章

**Comment by newraina** [comment]
不过看了下我的是可以的，你的博客哪里好像确实搜不出来...你有改动过啥吗？

**Comment by zhyt0520** [comment]
我只把head里面的fonts.useso.com字体注释掉了，其他地方没改过

**Comment by zhyt0520** [comment]
跟php的配置有关系吗？我现在用的万网的主机，一些php函数被禁用了
![Uploading snipaste_20170207_112854.png…]()

**Comment by zhyt0520** [comment]
跟php的配置有关系吗？我现在用的万网的主机，一些php函数被禁用了
![](https://ooo.0o0.ooo/2017/02/07/5899400c10811.png)

**Comment by newraina** [comment]
目前我也不清楚，可能不是主题的问题，可以在这里提问试试：http://forum.typecho.org/

**Comment by zhyt0520** [comment]
不是主题的问题，我用默认主题同样的毛病……
