### ISSUE TITLE
独立页面如何启用评论块

### ISSUE THREAD

**Issue by nolongerwait** [newraina/typecho-theme-NexTPisces#13]
因为开了一个“关于”的独立页面，页面尾部想开评论区，当做留言板使用。但是不知道该如何开启独立页面的评论。
独立页面的高级选项已经勾上了“允许评论”。
http://nolongerwait.com

**Comment by newraina** [comment]
默认好像不可以，可以试试在独立页面的模版里加上：
```php
<?php $this->need('comments.php'); ?>
```
