### ISSUE TITLE
列表前的·不显示

### ISSUE THREAD

**Issue by ju0594** [newraina/typecho-theme-NexTPisces#2]
就是这个符号`-`

**Comment by newraina** [comment]
是指无序列表每个列表项之前的圆圈？刚修复了~谢谢指出！

**Comment by ju0594** [comment]
@newraina 可以了，谢谢。顺便提下CDN那空默认会导致样式加载不出来…我放空才行。

**Comment by newraina** [comment]
@ju0594 默认应该是你的博客域名，可以检查下是不是，我的是可以的

**Comment by ju0594** [comment]
@newraina 默认是博客域名，反正放空能行也没事…
想问下cdn是怎么设置的？自主源站还是文件存储？

**Comment by newraina** [comment]
@ju0594 自主源站，如果是文件存储需要你手动把文件都上传到cdn上。

**Comment by ju0594** [comment]
@newraina 域名没备案，想手动上传，不知道是哪些文件上传到ftp的哪个文件夹？

**Comment by ju0594** [comment]
@newraina 知道为什么了…是我没有把主题文件夹改成NexTPisces的原因，所以cdn那栏默认的话会导致加载不出来…
cdn也弄好咯，问下是不是只加速css和js两项？

**Comment by newraina** [comment]
@ju0594 是的，没备案自主源站也可以用的
