### ISSUE TITLE
dist目录里的js和css是怎么构建的？

### ISSUE THREAD

**Issue by passerbythesun** [newraina/typecho-theme-NexTPisces#4]
你好，现在就在用你的这个主题，挺好用的。

如题，我修改了一些东西，但是每次修改`main.min.js`和`main.min.css`明显不是正确的方式。

我想知道楼主的`main.js`和`main.css`包含了哪些文件？还有是用什么工具压缩的呢？如果能写一个文档最好啦，多谢！

ps，我没有用过 `Hexo`，我估计`node.js`那边肯定有构建工具。

**Comment by newraina** [comment]
谢谢:) 这个主题好久没动过了，不少地方还挺粗糙，欢迎提出修改意见~

现在是靠gulp来打包，在主题目录下`npm i`安装好依赖，然后运行`gulp`就会打包所需的js和css到dist目录下,具体打包了啥文件,可以看看根目录下的gulpfile.js @passerbythesun

**Comment by passerbythesun** [comment]
刚装了个`node.js`，发现了问题所在，没想到楼主 @newraina  已经回复了

`node.js``Hexo`估计有空我也得玩玩了，不然太落伍了
