### ISSUE TITLE
新建的独立页面无法在侧边栏上输出。

### ISSUE THREAD

**Issue by xMuu** [newraina/typecho-theme-NexTPisces#6]
如题所示，新建了个About页面，但是并不会在sidebar上出现。这是有目的呢还是忘记加入了。

**Comment by newraina** [comment]
@xMuu 确认下在后台的设置里有没有选中这个页面？

**Comment by xMuu** [comment]
@newraina 后台设置该页面为公开页面了。也找不到哪里可以设置输出页面了。

**Comment by newraina** [comment]
好久没管这块了 😢 

https://github.com/newraina/typecho-theme-NexTPisces/blob/master/functions.php#L33

这是侧边栏配置的源码，都是写死的。

如果你要加侧边栏链接，也可以直接加在：

https://github.com/newraina/typecho-theme-NexTPisces/blob/master/header.php#L84

**Comment by zhyt0520** [comment]
@xMuu @newraina 我刚试了一下，成功加了一个 about 页面
1、页面的 slug 设置成 about
2、在 functions.php 33 行这里，第二个参数的数组加一个元素
![snipaste20170211_012136.png](https://ooo.0o0.ooo/2017/02/11/589df7ea8ba59.png)
3、变成这样
![snipaste20170211_012342.png](https://ooo.0o0.ooo/2017/02/11/589df7ea8b69d.png)
4、在后台设置外观处勾选“关于”，保存设置

**Comment by newraina** [comment]
@zhyt0520 谢谢~
