### ISSUE TITLE
侧边栏居左的主题如何设置呢

### ISSUE THREAD

**Issue by qhxin** [newraina/typecho-theme-NexTPisces#7]

**Comment by newraina** [comment]
是指侧边栏显示哪些链接吗？

现在基本算是写死状态，可以参考：#6

**Comment by qhxin** [comment]
@newraina 不是显示链接，嗯我想换成你博客那样的排版风格，但现在不是这样的，也找不到地方设置，你的博客是怎么做的呢

**Comment by newraina** [comment]
我也用的这主题，难道我们两的主题长的不一样？

**Comment by qhxin** [comment]
不一样呢，[http://www.qhxin.com](http://www.qhxin.com)，，，，好奇怪 @newraina

**Comment by newraina** [comment]
额，你用的不是我的主题，是这个 https://github.com/zgq354/typecho-theme-next

**Comment by qhxin** [comment]
身败名裂。。。。居然搞错了。。

**Comment by newraina** [comment]
😢
