### ISSUE TITLE
不知为何文章页面和分类页面打开就是404

### ISSUE THREAD

**Issue by JorenBai** [newraina/typecho-theme-NexTPisces#9]
如题，不知是何原因，在侧边点开文章页面或者分类页面就是404

**Comment by newraina** [comment]
可以参考 README 中的使用方法：

> 新建分类页，缩略名为categories，自定义模板选择categories
新建归档页，缩略名为archive，自定义模板选择archives
新建标签页，缩略名为tags，自定义模板选择tags

没有上述操作就会 404
